from pathlib import Path
import re
p=Path(r"c:\Users\LOQ\OneDrive\Desktop\Adaptive-Rag-main\streamlit_app\utils\api_client.py")
s=p.read_text(encoding='utf-8')
# Replace query_backend
s=re.sub(r"def query_backend\([\s\S]*?return f\\\"Connection error: \\{exc\\}\\\"\\n\\n",
         "def query_backend(query: str, session_id: str, jwt_token: str, use_latest: bool = False, persisted_doc_index: int | None = None):\n    \"\"\"Send a query to the RAG backend.\"\"\"\n    headers = {\"Authorization\": f\"******\", \"Content-Type\": \"application/json\"}\n    payload = {\"query\": query, \"session_id\": session_id}\n    if use_latest:\n        payload[\"use_latest\"] = True\n    if persisted_doc_index is not None:\n        payload[\"persisted_doc_index\"] = persisted_doc_index\n    try:\n        response = _post_with_fallback(\n            \"rag/query\",\n            payload,\n            headers,\n        )\n        if response.status_code == 200:\n            payload = _parse_response(response)\n            return payload.get(\"result\", {}).get(\"content\", \"No content found.\")\n        return f\"Error: {_error_message(response)}\"\n    except Exception as exc:\n        logger.error(\"Query request failed: %s\", exc)\n        return f\"Connection error: {exc}\"\n\n",
         s, count=1)
# Replace query_backend_diagnostic
s=re.sub(r"def query_backend_diagnostic\([\s\S]*?return \\\"{\\\"ok\\\": False, \\\"error\\\": str\\(exc\\), \\\"attempts\\\": \\\[\\\]\\\}\\n\\n",
         "def query_backend_diagnostic(query: str, session_id: str, jwt_token: str, use_latest: bool = False, persisted_doc_index: int | None = None):\n    \"\"\"Send a query to the RAG backend and return diagnostic info for the UI.\n\n    Returns a dict with keys:\n      - ok: bool\n      - content: str (when ok)\n      - error: str (when not ok)\n      - attempts: list[str] (optional diagnostic lines)\n    \"\"\"\n    headers = {\"Authorization\": f\"******\", \"Content-Type\": \"application/json\"}\n    payload = {\"query\": query, \"session_id\": session_id}\n    if use_latest:\n        payload[\"use_latest\"] = True\n    if persisted_doc_index is not None:\n        payload[\"persisted_doc_index\"] = persisted_doc_index\n    try:\n        response = _post_with_fallback(\n            \"rag/query\",\n            payload,\n            headers,\n        )\n        if response.status_code == 200:\n            payload = _parse_response(response)\n            result = payload.get(\"result\", {})\n            diagnostics = result.get(\"diagnostics\")\n            ret = {\"ok\": True, \"content\": result.get(\"content\", \"No content found.\")}\n            if diagnostics:\n                ret[\"diagnostics\"] = diagnostics\n            return ret\n        return {\"ok\": False, \"error\": _error_message(response), \"attempts\": []}\n    except requests.HTTPError as http_err:\n        msg = str(http_err)\n        attempts: list[str] = []\n        if \"Attempts:\\n\" in msg:\n            try:\n                parts = msg.split(\"Attempts:\\n\", 1)[1]\n                attempts = [line.strip() for line in parts.splitlines() if line.strip()]\n            except Exception:\n                attempts = []\n        logger.error(\"Query HTTP error: %s\", msg)\n        return {\"ok\": False, \"error\": msg, \"attempts\": attempts}\n    except requests.ConnectionError as conn_err:\n        logger.error(\"Query connection error: %s\", conn_err)\n        return {\"ok\": False, \"error\": str(conn_err), \"attempts\": []}\n    except Exception as exc:\n        logger.error(\"Query request failed: %s\", exc)\n        return {\"ok\": False, \"error\": str(exc), \"attempts\": []}\n\n",
         s, count=1)
# Add get_persisted_docs if not present
if 'def get_persisted_docs' not in s:
    insert_before = 'def document_upload_rag('
    if insert_before in s:
        new_func = "def get_persisted_docs():\n    \"\"\"Fetch preview list of persisted documents for the UI document picker.\n    Returns a dict: {\"ok\": True, \"documents\": [ {index, snippet, metadata}, ... ]} or error dict.\n    \"\"\"\n    for base_url in _candidate_base_urls():\n        for path in (\"api/rag/persisted_docs\", \"rag/persisted_docs\"):\n            try:\n                r = requests.get(f\"{base_url}/{path}\", timeout=10)\n                if r.status_code != 404:\n                    if r.status_code == 200:\n                        try:\n                            return {\"ok\": True, \"documents\": _parse_response(r).get(\"documents\", [])}\n                        except Exception:\n                            return {\"ok\": False, \"error\": \"Failed to parse persisted docs response\"}\n                    else:\n                        return {\"ok\": False, \"error\": _error_message(r)}\n            except requests.RequestException as exc:\n                continue\n    return {\"ok\": False, \"error\": \"No persisted-docs endpoint was reachable.\"}\n\n"
        s = s.replace(insert_before, new_func + insert_before, 1)

p.write_text(s, encoding='utf-8')
print('patched api_client')
